#!/usr/bin/env bash
#
# Run after a hotfix is started
#
# Arguments:
# $1 hotfix-name
# $2 hotfix-branch
# $3 working-branch
# $4 hotfix-source-branch

NAME=$1
BRANCH=$2
WORKING=$3
BASE=$4

# Implement Script Here

exit 0
