#!/usr/bin/env bash
#
# Run before a release is started
# If this scripts exits with a non-zero code, the operation is canceled
#
# Arguments:
# $1 version
# $2 release-branch
# $3 working-branch

VERSION=$1
BRANCH=$2
WORKING=$3

# Implement Script Here

exit 0
